"""The NGAM -> growth slope is a function of the regime, and these pin every half of that.

s_ATP was carried in `bridge/maintenance_calibration.py` and `bridge/stress_energetics.py` as
one number, 0.004642 /h per mmol ATP/gDW/h, tagged MEASURED, and defended by an invariance:
identical at glucose -1.0, -1.5 and -10.0. The invariance was real. Every row it was measured
on had ``oxygen_lower_bound = -1000.0`` and secreted no ethanol, so it was measured across the
carbon supply on a fully respiratory cell -- the one axis that does not move the slope.

At `fba/physiology.REFERENCE_AEROBIC_BATCH`, the operating point this repository validates its
GEM against, the cell ferments and the slope is 2.32x larger. Four things follow and each has
tests below:

  * the slope is per-regime and the regimes are SOLVED, not asserted -- so they are checked
    against `outputs/maintenance_scale.csv` cell by cell, and against Yeast9 itself under
    ``integration``;
  * the ablation is stated against a named floor, `MEASURED_GROWTH_RATE_SE`, INCLUDING the
    half where it fails -- at the measured maintenance total the regime is not resolvable;
  * a point nobody solved is REFUSED rather than interpolated, because the slope steps;
  * the tag is MODEL-DERIVED / IN_SILICO, and a test fails if anything calls it measured.
"""

from __future__ import annotations

import pathlib

import pytest

from ystwin import paths
from ystwin.bridge.maintenance_calibration import (
    ETHANOL_DETECTION_MMOL_PER_GDCW_H,
    IN_SILICO,
    MAINTENANCE_REGIMES,
    REFERENCE_REGIME,
    MaintenanceRegime,
    Refused,
    regime_for,
    regime_label,
)
from ystwin.bridge.stress_energetics import maintenance_from_reporter
from ystwin.fba.physiology import REFERENCE_AEROBIC_BATCH
from ystwin.generator.panel_experiment import MEASURED_GROWTH_RATE_SE

NGAM_REACTION = "r_4046"
GLUCOSE_EXCHANGE = "r_1714"
OXYGEN_EXCHANGE = "r_1992"
ETHANOL_EXCHANGE = "r_1761"

#: The two NGAM totals the latent branch spans: the measured full-stress maintenance and the
#: envelope `latent_bridge` asserts. Both from the modules, neither retyped.
MEASURED_TOTAL = maintenance_from_reporter(1.0, 1.0).ngam_high
ASSERTED_TOTAL = 7.2


@pytest.fixture(scope="module")
def table():
    """`outputs/maintenance_scale.csv`, or a skip. Regenerated by scripts/maintenance_scale.py."""
    import pandas as pd

    path = pathlib.Path(paths.REPO_ROOT) / "outputs" / "maintenance_scale.csv"
    if not path.exists():
        pytest.skip("outputs/maintenance_scale.csv absent; run scripts/maintenance_scale.py")
    return pd.read_csv(path)


#: Bound match tolerance for selecting a regime's row out of the CSV. The bounds are written
#: unrounded, so this only absorbs the float round trip through the text file.
_BOUND_TOLERANCE = 1e-9

#: How far a shipped field may sit from a fresh Yeast9 solve. Two sources, both named: the
#: table rounds to six decimals (<= 5e-7), and glpk's simplex settles on optima that differ
#: at ~1e-7 depending on the basis it warm-starts from.
_SOLVE_TOLERANCE = 2e-6


def _row(table, regime):
    """The one row of the CSV at this regime's bounds.

    Not ``== pytest.approx(...)``: on a pandas Series that comparison returns all-False
    rather than an elementwise match, which selects nothing and passes nothing.
    """
    selected = table[
        ((table["glucose_lower_bound_mmol_per_gdcw_h"]
          - regime.glucose_lower_bound_mmol_per_gdcw_h).abs() <= _BOUND_TOLERANCE)
        & ((table["oxygen_lower_bound_mmol_per_gdcw_h"]
            - regime.oxygen_lower_bound_mmol_per_gdcw_h).abs() <= _BOUND_TOLERANCE)]
    assert len(selected) == 1, f"{regime.name} selects {len(selected)} rows, not one"
    return selected.iloc[0]


class TestTheSlopeIsNotAScalar:
    """The finding. If these ever pass trivially the correction has been undone."""

    def test_the_respiratory_and_fermenting_slopes_differ(self):
        respiratory = MAINTENANCE_REGIMES["respiratory_glucose_excess"]
        fermenting = REFERENCE_REGIME

        assert (fermenting.ngam_growth_slope_per_h_per_mmol_atp
                > 2 * respiratory.ngam_growth_slope_per_h_per_mmol_atp)

    def test_the_repositorys_validated_operating_point_ferments(self):
        """The reason the respiratory branch was the wrong one to ship: nothing this
        repository solves at sits on it."""
        assert REFERENCE_REGIME.ferments
        assert REFERENCE_AEROBIC_BATCH.ethanol_secretion > 0

    def test_the_reference_regime_is_the_physiology_reference_and_not_a_retyped_copy(self):
        assert (REFERENCE_REGIME.glucose_lower_bound_mmol_per_gdcw_h
                == -REFERENCE_AEROBIC_BATCH.glucose_uptake)
        assert (REFERENCE_REGIME.oxygen_lower_bound_mmol_per_gdcw_h
                == -REFERENCE_AEROBIC_BATCH.oxygen_uptake)

    def test_every_oxygen_unlimited_regime_respires(self):
        for regime in MAINTENANCE_REGIMES.values():
            if regime.oxygen_lower_bound_mmol_per_gdcw_h == -1000.0:
                assert not regime.ferments, regime.name

    def test_the_invariance_that_was_quoted_is_real_and_is_across_glucose_only(self):
        """Both oxygen-free regimes carry the SAME slope at a tenfold difference in glucose.
        The old claim was true; it was the branch it was true on that was never stated."""
        limited = MAINTENANCE_REGIMES["respiratory_glucose_limited"]
        excess = MAINTENANCE_REGIMES["respiratory_glucose_excess"]

        assert (limited.glucose_lower_bound_mmol_per_gdcw_h
                != excess.glucose_lower_bound_mmol_per_gdcw_h)
        assert (limited.ngam_growth_slope_per_h_per_mmol_atp
                == excess.ngam_growth_slope_per_h_per_mmol_atp)


class TestTheAblationAgainstANamedFloor:
    """Criterion (a). The observable is the specific growth rate and the floor is
    `generator/panel_experiment.MEASURED_GROWTH_RATE_SE` = 0.0117 /h, the standard error of a
    growth rate fitted off a real OD trace -- not the plate CV, which measures reporter
    activity and has no business judging an /h.
    """

    @staticmethod
    def _error(regime, ngam):
        respiratory = MAINTENANCE_REGIMES["respiratory_glucose_excess"]
        return abs(regime.ngam_growth_slope_per_h_per_mmol_atp
                   - respiratory.ngam_growth_slope_per_h_per_mmol_atp) * ngam

    def test_removing_the_regime_moves_growth_past_the_floor_at_the_asserted_total(self):
        assert self._error(REFERENCE_REGIME, ASSERTED_TOTAL) > MEASURED_GROWTH_RATE_SE

    def test_it_clears_the_floor_by_more_than_threefold(self):
        assert self._error(REFERENCE_REGIME, ASSERTED_TOTAL) > 3 * MEASURED_GROWTH_RATE_SE

    def test_at_the_MEASURED_total_it_does_NOT_clear_the_floor(self):
        """The half of the ablation that argues against the change, pinned so it cannot be
        quietly dropped. At the maintenance scale PMID 40181231 actually measures, the regime
        moves growth by less than the growth assay can resolve."""
        assert self._error(REFERENCE_REGIME, MEASURED_TOTAL) < MEASURED_GROWTH_RATE_SE

    def test_the_crossover_sits_between_the_measured_and_asserted_totals(self):
        """So the statement is exact rather than a pair of anecdotes: name the NGAM above
        which the regime is worth carrying."""
        respiratory = MAINTENANCE_REGIMES["respiratory_glucose_excess"]
        gap = abs(REFERENCE_REGIME.ngam_growth_slope_per_h_per_mmol_atp
                  - respiratory.ngam_growth_slope_per_h_per_mmol_atp)
        crossover = MEASURED_GROWTH_RATE_SE / gap

        assert MEASURED_TOTAL < crossover < ASSERTED_TOTAL

    def test_an_oxygen_free_regime_ablates_to_nothing(self):
        """The control. Ablating the regime where the regime IS the respiratory one must
        move nothing, or the test above is measuring arithmetic rather than metabolism."""
        assert self._error(MAINTENANCE_REGIMES["respiratory_glucose_limited"],
                           ASSERTED_TOTAL) == 0.0


class TestTheReductionToOneSlopePerRegime:
    """Criterion (d), in growth units rather than as a relative spread. A regime replaces a
    solve with ``penalty = slope * NGAM``; that is licensed only where one slope reproduces
    the solve to better than the assay that would measure it."""

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    def test_a_single_slope_is_within_the_growth_floor(self, name):
        regime = MAINTENANCE_REGIMES[name]

        assert regime.slope_linearity_growth_error_per_h < MEASURED_GROWTH_RATE_SE

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    def test_the_penalty_is_linear_in_the_bound(self, name):
        regime = MAINTENANCE_REGIMES[name]

        assert regime.growth_penalty_per_h(4.0) == pytest.approx(
            2 * regime.growth_penalty_per_h(2.0))

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    def test_growth_falls_below_the_unconstrained_rate(self, name):
        regime = MAINTENANCE_REGIMES[name]

        assert regime.growth_per_h(1.0) < regime.growth_at_zero_ngam_per_h


class TestItRefusesRatherThanInterpolating:
    """Criterion (b). Every regime here is a solved point; a point between two of them is not
    a regime, because the slope steps when overflow switches on."""

    def test_an_unsolved_operating_point_is_refused(self):
        with pytest.raises(KeyError, match="REFUSED"):
            regime_for(-5.0, -2.5)

    def test_the_refusal_names_the_points_that_do_exist_and_how_to_add_one(self):
        with pytest.raises(KeyError, match="maintenance_scale.py"):
            regime_for(-5.0, -2.5)

    @pytest.mark.parametrize("oxygen", [-0.5, -5.0, -100.0])
    def test_a_96_well_plate_is_refused_because_nobody_measured_its_oxygen(self, oxygen):
        """The caveat this correction ships with. A shaken 96-well plate has no measured kLa
        in this repository, so its oxygen uptake bound is unknown -- and since the slope
        steps at the onset of overflow, an unknown oxygen bound is a REFUSAL and not the
        nearest solved point, at the reference glucose as much as anywhere else."""
        with pytest.raises(KeyError, match="REFUSED"):
            regime_for(-REFERENCE_AEROBIC_BATCH.glucose_uptake, oxygen)

    def test_a_solved_point_resolves(self):
        assert regime_for(-10.0, -1000.0).name == "respiratory_glucose_excess"
        assert regime_for(-REFERENCE_AEROBIC_BATCH.glucose_uptake,
                          -REFERENCE_AEROBIC_BATCH.oxygen_uptake) is REFERENCE_REGIME

    def test_a_growth_penalty_without_a_regime_is_a_refusal_and_not_a_default(self):
        result = maintenance_from_reporter(1.0, 1.0)

        assert isinstance(result.growth_penalty_per_h, Refused)

    def test_that_refusal_raises_on_float_rather_than_evaluating(self):
        result = maintenance_from_reporter(1.0, 1.0)

        with pytest.raises(TypeError, match="REFUSED"):
            float(result.growth_penalty_per_h)

    def test_the_refusal_is_falsey_so_a_truth_test_cannot_mistake_it_for_a_number(self):
        assert not Refused("because")

    def test_the_refusal_says_how_big_the_thing_it_will_not_guess_is(self):
        """A refusal that does not say what it is worth is an obstacle, not a finding."""
        result = maintenance_from_reporter(1.0, 1.0)

        assert "2.32x" in repr(result.growth_penalty_per_h)

    def test_supplying_a_regime_lifts_it(self):
        result = maintenance_from_reporter(1.0, 1.0, regime=REFERENCE_REGIME)
        low, high = result.growth_penalty_per_h

        assert 0 < low <= high

    def test_the_two_regimes_give_different_growth_costs_for_the_same_reading(self):
        """End to end: the same reporter reading, two operating points, two answers. This is
        the behaviour the whole change exists to produce."""
        fermenting = maintenance_from_reporter(1.0, 1.0, regime=REFERENCE_REGIME)
        respiring = maintenance_from_reporter(
            1.0, 1.0, regime=MAINTENANCE_REGIMES["respiratory_glucose_excess"])

        assert (fermenting.growth_penalty_per_h[1]
                > 2 * respiring.growth_penalty_per_h[1])

    def test_the_summary_says_which_regime_priced_it(self):
        text = maintenance_from_reporter(1.0, 1.0, regime=REFERENCE_REGIME).summary()

        assert "aerobic_batch_reference" in text

    def test_the_summary_quotes_no_growth_cost_when_nothing_priced_it(self):
        """It reports the NGAM interval and stops. The refusal lives on
        :attr:`growth_penalty_per_h`, which raises on ``float``; putting it in the summary
        too would put the word REFUSED into every regime-free line and would collide with
        `tests/test_stress_energetics.py`, where REFUSED means the NGAM value is unusable."""
        assert "growth" not in maintenance_from_reporter(1.0, 1.0).summary()

    def test_a_bound_past_the_no_growth_threshold_is_refused(self):
        """Extrapolating a linear penalty past the threshold returns more growth lost than
        there is growth. The LP is infeasible there, which is not the same as slow."""
        with pytest.raises(ValueError, match="no-growth threshold"):
            REFERENCE_REGIME.growth_penalty_per_h(
                REFERENCE_REGIME.no_growth_ngam_mmol_atp_per_gdw_h + 1.0)

    def test_a_negative_bound_is_refused(self):
        with pytest.raises(ValueError, match="non-negative"):
            REFERENCE_REGIME.growth_penalty_per_h(-1.0)


class TestTheTagIsInSilicoAndNotMeasured:
    """House rule 3. The slope was tagged MEASURED and is a linear-program gradient."""

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    def test_every_regime_carries_the_in_silico_tag(self, name):
        assert MAINTENANCE_REGIMES[name].provenance.startswith("MODEL-DERIVED / IN_SILICO")

    def test_the_tag_names_the_model_file_and_the_script(self):
        assert "yeast-GEM.xml.gz" in IN_SILICO
        assert "maintenance_scale.py" in IN_SILICO

    def test_no_regime_claims_a_culture_was_read(self):
        for regime in MAINTENANCE_REGIMES.values():
            assert "MEASURED:" not in regime.provenance

    def test_the_summary_carries_the_tag_to_the_reader(self):
        assert "MODEL-DERIVED / IN_SILICO" in REFERENCE_REGIME.summary()


class TestTheRegimeLabelReadsTheMechanismAndNotTheBound:
    """Overflow is what changes the slope, so the label reads the ethanol exchange. A cell can
    be oxygen-capped and still respire everything it takes up -- glucose -1.0 against oxygen
    -3.7 does exactly that, and calling it fermentative on its oxygen bound would be wrong."""

    def test_zero_ethanol_is_respiratory(self):
        assert regime_label(0.0) == "respiratory"

    def test_a_real_overflow_flux_is_fermentative(self):
        assert regime_label(15.923) == "fermentative"

    def test_solver_noise_is_not_overflow(self):
        assert regime_label(0.1 * ETHANOL_DETECTION_MMOL_PER_GDCW_H) == "respiratory"

    @pytest.mark.parametrize("threshold", [1e-12, 1e-9, 1e-6, 1e-3, 1e-2, 0.1])
    def test_no_label_in_the_table_depends_on_where_the_threshold_sits(self, table, threshold):
        """The free-scalar gate on the one scalar this piece chose.
        ``ETHANOL_DETECTION_MMOL_PER_GDCW_H`` is ASSERTED, so it is swept: every respiratory
        row secretes exactly zero and every fermenting row at least 0.145, so eleven decades
        of threshold assign the same sixteen labels and no result rests on the choice."""
        for row in table.itertuples():
            expected = ("fermentative"
                        if row.ethanol_at_zero_ngam_mmol_per_gdcw_h > threshold
                        else "respiratory")

            assert expected == row.regime


class TestTheRegimesAreSolvedAndNotAsserted:
    """Every field of every shipped regime is a cell of `outputs/maintenance_scale.csv`. A
    dataclass full of hand-typed numbers would look identical and mean nothing."""

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    @pytest.mark.parametrize("field, column", [
        ("growth_at_zero_ngam_per_h", "growth_at_zero_ngam_per_h"),
        ("ethanol_at_zero_ngam_mmol_per_gdcw_h", "ethanol_at_zero_ngam_mmol_per_gdcw_h"),
        ("ngam_growth_slope_per_h_per_mmol_atp", "ngam_slope_per_h_per_mmol_atp"),
        ("no_growth_ngam_mmol_atp_per_gdw_h", "no_growth_ngam_mmol_atp_per_gdw_h"),
        ("slope_linearity_growth_error_per_h", "slope_linearity_growth_error_per_h"),
    ])
    def test_the_shipped_value_is_the_cell(self, table, name, field, column):
        regime = MAINTENANCE_REGIMES[name]

        assert getattr(regime, field) == pytest.approx(_row(table, regime)[column])

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    def test_the_shipped_label_is_the_cell(self, table, name):
        regime = MAINTENANCE_REGIMES[name]

        assert regime.regime == _row(table, regime)["regime"]

    def test_the_table_sweeps_oxygen_and_not_only_glucose(self, table):
        """The defect that produced the wrong branch: one bound varied, the other printed."""
        assert table["oxygen_lower_bound_mmol_per_gdcw_h"].nunique() > 1
        assert table["glucose_lower_bound_mmol_per_gdcw_h"].nunique() > 1

    def test_the_table_contains_both_regimes(self, table):
        assert set(table["regime"]) == {"respiratory", "fermentative"}

    def test_the_table_names_the_floor_it_is_judged_against(self, table):
        assert (table["growth_assay_floor_per_h"] == MEASURED_GROWTH_RATE_SE).all()

    def test_the_rows_where_a_single_slope_fails_are_kept_in_the_table(self, table):
        """And deliberately NOT shipped as regimes. They are the evidence for the piecewise
        story -- raising NGAM pushes a respiring cell into overflow -- so losing them would
        lose the mechanism."""
        bent = table[table["slope_linearity_growth_error_per_h"] > MEASURED_GROWTH_RATE_SE]

        assert not bent.empty
        assert (bent["regime"] != bent["regime_at_top_probe"]).all()

    def test_no_shipped_regime_is_one_of_those_rows(self, table):
        for regime in MAINTENANCE_REGIMES.values():
            row = _row(table, regime)
            assert row["slope_linearity_growth_error_per_h"] < MEASURED_GROWTH_RATE_SE


@pytest.mark.integration
class TestYeast9SaysWhatTheRegimesSay:
    """The strongest check available: reopen the model and recompute. A table and a dataclass
    can agree with each other while both being stale, which is how the oxygen bound stayed at
    -1000.0 in a column three docstrings quoted from."""

    @staticmethod
    def _growth(model, ngam):
        """None where the constraint is infeasible.

        The warning filter is narrow and deliberate: the suite runs with
        ``filterwarnings = ["error"]``, and cobra's infeasible-status warning is an expected
        result when a probe is placed past the threshold rather than a defect.
        """
        import warnings

        with model:
            model.reactions.get_by_id(NGAM_REACTION).bounds = (ngam, 1000.0)
            with warnings.catch_warnings():
                warnings.filterwarnings("ignore", "Solver status is", UserWarning)
                solution = model.optimize()
            return (solution.objective_value
                    if solution.status == "optimal" and solution.objective_value is not None
                    else None)

    @pytest.fixture
    def at_regime(self, yeast_gem):
        """Set the two exchange bounds, and PUT THEM BACK. ``yeast_gem`` is session-scoped,
        so a bound written here without the context manager leaks into every later test."""
        with yeast_gem:
            def configure(regime):
                yeast_gem.reactions.get_by_id(GLUCOSE_EXCHANGE).lower_bound = (
                    regime.glucose_lower_bound_mmol_per_gdcw_h)
                yeast_gem.reactions.get_by_id(OXYGEN_EXCHANGE).lower_bound = (
                    regime.oxygen_lower_bound_mmol_per_gdcw_h)
                return yeast_gem
            yield configure

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    def test_the_shipped_slope_is_the_models_slope(self, at_regime, name):
        regime = MAINTENANCE_REGIMES[name]
        model = at_regime(regime)
        base = self._growth(model, 0.0)

        slope = (base - self._growth(model, 1.0)) / 1.0

        assert slope == pytest.approx(
            regime.ngam_growth_slope_per_h_per_mmol_atp, abs=_SOLVE_TOLERANCE)

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    def test_the_shipped_unconstrained_growth_is_the_models(self, at_regime, name):
        regime = MAINTENANCE_REGIMES[name]

        assert self._growth(at_regime(regime), 0.0) == pytest.approx(
            regime.growth_at_zero_ngam_per_h, abs=_SOLVE_TOLERANCE)

    @pytest.mark.parametrize("name", sorted(MAINTENANCE_REGIMES))
    def test_the_shipped_overflow_flux_is_the_models(self, at_regime, name):
        regime = MAINTENANCE_REGIMES[name]
        model = at_regime(regime)

        with model:
            model.reactions.get_by_id(NGAM_REACTION).bounds = (0.0, 1000.0)
            ethanol = float(model.optimize().fluxes[ETHANOL_EXCHANGE])

        assert ethanol == pytest.approx(
            regime.ethanol_at_zero_ngam_mmol_per_gdcw_h, abs=5e-4)

    def test_the_model_stops_growing_where_the_regime_says_it_does(self, at_regime):
        regime = REFERENCE_REGIME
        model = at_regime(regime)
        threshold = regime.no_growth_ngam_mmol_atp_per_gdw_h

        assert self._growth(model, threshold - 0.05) > 0
        assert not self._growth(model, threshold + 0.05)

    def test_the_two_slopes_are_not_the_same_number_on_the_model_either(self, at_regime):
        """The ablation, recomputed rather than read: the same NGAM bound costs a fermenting
        cell more growth than a respiring one by more than the growth assay's floor."""
        fermenting = at_regime(REFERENCE_REGIME)
        base = self._growth(fermenting, 0.0)
        cost_fermenting = base - self._growth(fermenting, ASSERTED_TOTAL)

        respiratory = MAINTENANCE_REGIMES["respiratory_glucose_excess"]
        respiring = at_regime(respiratory)
        base_r = self._growth(respiring, 0.0)
        cost_respiring = base_r - self._growth(respiring, ASSERTED_TOTAL)

        assert cost_fermenting - cost_respiring > MEASURED_GROWTH_RATE_SE

    def test_raising_ngam_can_switch_a_respiring_cell_into_overflow(self, at_regime):
        """The mechanism behind the rows that are in the table and not in the regime set: the
        NGAM bound is itself part of the regime. At glucose -1.0 against oxygen -3.7 the model
        respires everything up to NGAM 7.2 and ferments by 10.0."""
        model = at_regime(MaintenanceRegime(
            name="probe", glucose_lower_bound_mmol_per_gdcw_h=-1.0,
            oxygen_lower_bound_mmol_per_gdcw_h=-REFERENCE_AEROBIC_BATCH.oxygen_uptake,
            growth_at_zero_ngam_per_h=0.0, ethanol_at_zero_ngam_mmol_per_gdcw_h=0.0,
            ngam_growth_slope_per_h_per_mmol_atp=0.0,
            no_growth_ngam_mmol_atp_per_gdw_h=1.0,
            slope_linearity_growth_error_per_h=0.0))

        def ethanol(ngam):
            with model:
                model.reactions.get_by_id(NGAM_REACTION).bounds = (ngam, 1000.0)
                return float(model.optimize().fluxes[ETHANOL_EXCHANGE])

        assert regime_label(ethanol(ASSERTED_TOTAL)) == "respiratory"
        assert regime_label(ethanol(10.0)) == "fermentative"
